---
title: 'Texas: Visualization 3'
author: "Xianbin Cheng"
date: "February 5, 2019"
output: html_document
---

# Objective

  * Visualize the Texas corn data after cleaning up NA's. 
  
# Method

1. Load the libraries and read in the file.

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
```

```{r}
df = read.csv("Texas_Conc_Class_528obs_02_05_19.csv", header = TRUE, row.names = 1)
str(df)
```

```{r}
# How many H, M, L's for each mycotoxin?
summary(df$AF_class)
summary(df$FM_class)

# How many samples are there?
summary(df$plate %>% as.factor())
```

2. Minor clean-up. 

```{r}
colnames(df)[c(6,7)] = c("<LOD.AF", "<LOD.FM")

df$AF_class = factor(df$AF_class, levels = c("H", "M", "L"))
df$FM_class = factor(df$FM_class, levels = c("H", "M", "L"))
```

# Result

1. Create a histogram for mycotoxin distribution grouped by class. Put the x axis on the log scale. It only shows the kernels with mycotoxin concentration > LOD.

```{r}
AF_hist = ggplot(data = subset(x = df, subset = `<LOD.AF` == 0))+
  geom_histogram(aes(x = AF.ppb., fill = AF_class), bins = 50) +
  labs(x = "Aflatoxin concentration (ppb)", y = "Number of Kernels")+
  scale_x_log10(breaks = c(1e-2, 1e-1, 1, 1e1, 1e2, 1e3, 1e4, 1e5)) +
  scale_fill_discrete(name = "Single Kernel Aflatoxin Level", labels = c("[AF]>=50", "[AF]<20")) +
  theme_classic() +
  theme(legend.position = "top")

AF_hist
```

```{r}
FM_hist = ggplot(data = subset(x = df, subset = `<LOD.FM` == 0))+
  geom_histogram(aes(x = FM.ppm., fill = FM_class), bins = 60) +
  labs(x = "Fumonisin concentration (ppm)", y = "Number of Kernels")+
  scale_x_log10(breaks = c(0.001, 0.01, 0.1, 1, 10, 100, 1000)) +
  scale_fill_discrete(name = "Single Kernel Fumonisin Level", labels = c("[FM]>=4", "1<=[FM]<4", "[FM]<1")) +
  theme_bw()+
  theme(legend.position = "top")

FM_hist
```

3. Create a bar chart for both aflatoxin and fumonisin grouped by class.

```{r, warning = FALSE}
barchart = ggplot(data = df)+
  geom_bar(aes(x = rep("Aflatoxin", nrow(df)), fill = AF_class), 
           position = "stack") +
  geom_bar(aes(x = rep("Fumonisin", nrow(df)), fill = FM_class), 
           position = "stack") +
  geom_text(stat="count", aes(x = rep("Aflatoxin", nrow(df)), 
                              fill = AF_class, 
                              label=..count..), 
            position = position_stack(vjust = 0.5)) +
  geom_text(stat="count", aes(x = rep("Fumonisin", nrow(df)), 
                              fill = FM_class, 
                              label=..count..), 
            position = position_stack(vjust = 0.5)) +
  labs(x = NULL, y = "Number of Kernels") +
  scale_fill_discrete(name = "Single Kernel Mycotoxin Level", labels = c("High", "Low", "Medium")) +
  theme_classic()+
  theme(legend.position = "top")

barchart
```

```{r, echo = FALSE, eval = FALSE}
pdf("Texas Corn Kernels ELISA Results after data cleaning (528obs).pdf")
  AF_hist
  FM_hist
  barchart
dev.off()
```

